# Overview

This is a listing of the indices available in Biodiverse,
ordered by the calculations used to generate them.
It is generated from the system metadata and contains all the 
information visible in the GUI, plus some additional details.

Most of the headings are self-explanatory.  For the others:

  * The *Subroutine* is the name of the subroutine used to call the function if you
    are using Biodiverse through a script.
  * The *Index* is the name of the index in the SPATIAL_RESULTS list, or if it is its own list
    then this will be its name.  These lists can contain a variety of values, but are usually
    lists of labels with some value, for example the weights used in an endemism calculation.
    The names of such lists typically end in "LIST", "ARRAY", "HASH", "LABELS" or "STATS".
  * *Grouping?* states whether or not the index can be used to define the grouping for a
    cluster or region grower analysis.  A blank value means it cannot be used for either.
  * The *Minimum number of neighbour sets* dictates whether or not a calculation or index will
    be run.  If you specify only one neighbour set then all those calculations that require
    two sets will be dropped from the analysis.  (This is always the case for calculations
    applied to cluster nodes as there is only one neighbour set, defined by the set of groups
    linked to the terminal nodes below a cluster node).  Note that many of the calculations
    lump neighbour sets 1 and 2 together.  See the
    [SpatialConditions](https://biogeospatial.github.io/biodiverse-spatial-conditions/)
    page for more details on neighbour sets.

Note that some calculations can provide different numbers of indices depending on the nature
of the BaseData set used.
This currently applies to the hierarchically partitioned endemism calculations (both
[central](#endemism-central-hierarchical-partition) and
[whole](#endemism-whole-hierarchical-partition)).

For space reasons, columns are not shown if all cells are empty.
